name: SimplePipeline

on: 
  push:
    branches: [main]

jobs: 
  lintTest:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          echo "Running Installing dependencies..."
          npm install
      - name: Run Linting
        run: |
          echo "Running Linting tests..."
          npm run lint
        env:
          CI: true
  secuityCheck:
    name: Security Check
    runs-on: ubuntu-latest
    steps:
      - name: Security Check
        run: |
          echo "Running Security Check..."
          sleep 5s
          echo "Running Security Check...1"
          sleep 5s
          echo "Running Security Check...2"
          sleep 5s
          echo "Running Security Check...3"
          sleep 5s
  deploy:
   name: Deployment
   runs-on: ubuntu-latest
   needs: [lintTest, secuityCheck]
   steps:
    - name: Install Dependencies
      run: |
        echo "Deployment in progress..."
        sleep 5s